// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/footer/footer.vue')['default']
    FooterPlayList: typeof import('./src/components/layout/footer/footerPlayList.vue')['default']
    Header: typeof import('./src/components/layout/header/header.vue')['default']
    IconPark: typeof import('./src/components/common/IconPark.vue')['default']
    Left_box: typeof import('./src/components/layout/main/components/left_box.vue')['default']
    Main: typeof import('./src/components/layout/main/main.vue')['default']
    PlayList: typeof import('./src/components/layout/main/components/playList.vue')['default']
    PlsyListNewSong: typeof import('./src/components/layout/main/components/plsyListNewSong.vue')['default']
    Right_box: typeof import('./src/components/layout/main/components/right_box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
